<?php
$pageTitle = '';
?>
<!DOCTYPE html>
<html lang="zh-Hant">

<head>
  <?php include("include/_meta.php"); ?>
</head>



<body>
  <div id="wrap" class="wrap">
    <?php include("include/_header.php"); ?>

    <div id="main" class="main">
      <!-- content 從這裡開始 -->
      <!-- //title -->


      <div class="bg-gray text-center font-l fon-weight-l">
        <p class="py-3">Practicing ESG philosophy, KONFU ENTERPRISE expects sustainable operation.</p>
        <p class="py-3">ESG stands for the abbreviations of the three English words, which is "Environmental,</p>
        <p>Social, and Governance".</p>
      </div>

      <!-- Environmental -->
      <h3 class="text-center my-3">Environmental</h3>
      <div class="container">
        <div class="row py-4 l-h-25">
          <div class="col-lg-6 text-left font-l fon-weight-l">
            <p>KONFU ENTERPRISE established in 1975, actually began to practice ESG's philosophy very early. Regarding the environment, for the waste oil generated by the operation of the factory, we purchase an oil filter, reuse the oil as much as possible and then </p>
          </div>
          <div class="col-lg-6 text-left font-l fon-weight-l">
            <p>recycle it, and adopt an environmentally friendly operation method. In addition, we uses reusable stainless steel tableware for lunch to reduce the use of disposable tableware.</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Social -->
    <div class="bg bg-gray">
      <h3 class="text-center">Social</h3>
      <div class="container">
        <div class="row py-4">
          <div class="col-lg-6  text-left font-l fon-weight-l l-h-25">
            <p class="my-3">Over the years, we have continued to give back to the society and allocated company surplus to support various charity activities.</p>
            <p class="my-3">In 2005, Chairman Mr. Char-Fu, Shea read the newspaper learned that the principal of Tainan Zuozhen Junior High School was worrying about the lack of nutritional lunch for students in the rural areas. Mr. Shea immediately went to visit the principal and started to provide students with nutritional lunch fee, various sponsorship activities such as transportation expenses and after-school tutoring expenses.</p>
            <p class="my-3">Later, in order to consider sustainable good deeds, in 2013, Mr.Shea donated USD 700,000 to set up the "Chen-Cheng Education Development Association" in the name of his deceased father to make good deeds more systematic and planned. Many suppliers and benevolent people also donated to support.</p>
          </div>
          <div class="col-lg-6 text-left font-l fon-weight-l l-h-25">
            <p class="my-3">At the beginning of the operation of the association, more efforts were made to tutor the dropouts, helping the dropouts of many middle schools to get on the right track. Then the Sunshine Youth Camp project was launched, which is mainly to cultivate youthful temperaments like sunshine, warmth, selfless devotion, brightness and equality. </p>
            <p class="my-3">Specific measures include: providing mountaineering equipment, building rock climbing fields, and donating nearly 500 bicycles to 17 schools to lead junior high school students to challenge the cycling around the Taiwan island, so that junior high school students who lack resources can get close to nature.
              In addition, he also sponsored weightlifting teams and supported the establishment of digital English classrooms. </p>
          </div>
        </div>
      </div>
      <!-- /social -->

      <div class="popup">
        <img class="m-1" src="./images/esg1.jpeg">
        <img class="m-1" src="./images/esg2.jpeg">
        <img class="m-1" src="./images/esg3.jpeg">
        <img class="m-1" src="./images/esg4.jpeg">
        <img class="m-1" src="./images/esg5.jpeg">
        <img class="m-1" src="./images/esg6.jpeg">
      </div>

      <div class="container">
        <div class="row">
          <div class="col col-lg-4 imgfit imgfit-3x2">
            <img class="" src="./images/esg1.jpeg">
          </div>
          <div class="col col-lg-4 imgfit imgfit-3x2">
            <img class="" src="./images/esg2.jpeg">
          </div>
          <div class="col col-lg-4 imgfit imgfit-3x2">
            <img class="" src="./images/esg3.jpeg">
          </div>
          <div class="col col-lg-4 imgfit imgfit-3x2">
            <img class="" src="./images/esg4.jpeg">
          </div>
          <div class="col col-lg-4 imgfit imgfit-3x2">
            <img class="" src="./images/esg5.jpeg">
          </div>
          <div class="col col-lg-4 imgfit imgfit-3x2">
            <img class="" src="./images/esg6.jpeg">
          </div>
        </div>

      </div>
      <div class="show">
        <div class="overlay"></div>
        <div class="img-show">
          <span>X</span>
          <img src="">
        </div>
      </div>

      <div class="container">
        <div class="row py-4">
          <div class="col-lg-6  text-left font-l fon-weight-l l-h-25">
            <p class="my-3">When natural catastrophes occur, such as the September 21 earthquake in Taiwan, the earthquake in Turkey, the tsunami in South Asia, and the tsunami in Japan, in the spirit of helping each other in the same boat, KONFU ENTERPRISE also donated money to help people in need.</p>
            <p class="my-3">During the COVID-19 epidemic, when masks were not easy to </p>

          </div>
          <div class="col-lg-6 text-left font-l fon-weight-l l-h-25">
            <p class="my-3">obtain, our suppliers also donated a lot of masks. Through us, we donated them to customers in France, Italy, Turkey, India, etc., so that they can prevent the invasion of the virus.</p>
            <p class="my-3">Regarding labor rights, the company provides additional childcare allowances to reduce the burden of childcare for colleagues. It also provides free health checks to care for the health of colleagues.</p>
          </div>
        </div>
      </div>
    </div> <!-- bg-gray -->

    <!-- Governance -->
    <h3 class="text-center my-3">Governance</h3>
    <div class="container">
      <div class="row py-4">
        <div class="col-lg-6 text-left font-l fon-weight-l">
          <p>KONFU ENTERPRISE will hold a shareholder meeting every quarter to uphold the spirit of openness and transparency and explain all operating conditions to shareholders.</p>
        </div>
        <div class="col-lg-6 text-left font-l fon-weight-l">
          <p>In addition, uphold the spirit of "creating profits and sharing together", we also let employees own shares in the company, so that employees can be more committed to the company.</p>
        </div>
      </div>
    </div>



    <div class="bg bg-gray">

      <div class="py-4">
        <div class=" text-center font-l fon-weight-l">
          <p class="my-3">Looking forward to the future, we will continue to follow ESG regulations and operate sustainably. We are grateful to all the customers and suppliers who trade with us, and we look forward to creating more business opportunities with more friends from all over the world who agree with us in the future, continue to give back to the society, and form a positive energy cycle.</p>
        </div>
      </div>

      <div class="popupthanks">
        <img class="m-1" src="./images/感謝狀1.jpeg">
        <img class="m-1" src="./images/感謝狀2.jpeg">
        <img class="m-1" src="./images/感謝狀3.jpeg">
        <img class="m-1" src="./images/感謝狀4.jpeg">
        <img class="m-1 thankspic" src="./images/感謝狀5.jpeg">
        <img class="m-1" src="./images/感謝狀6.jpeg">
        <img class="m-1" src="./images/感謝狀7.jpeg">
      </div>
      <div class="show">
        <div class="overlay"></div>
        <div class="img-show">
          <span>X</span>
          <img src="">
        </div>
      </div>

    </div> <!-- bg-gray -->
    <!--End of main-->

    <?php include("include/_footer.php"); ?>


  </div>
  <!--End of wrap-->

  <?php include("include/_js.php"); ?>
  <!-- plugin js -->
  <!-- Swiper Slider -->
  <script src="js/swiper/swiper-bundle.min.js"></script>


  <script>
    var swiper = new Swiper(".mySwiper", {
      cssMode: true,
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
      pagination: {
        el: ".swiper-pagination",
      },
      mousewheel: true,
      keyboard: true,
    });


    $(function() {
      "use strict";

      $(".popup img").click(function() {
        var $src = $(this).attr("src");
        $(".show").fadeIn();
        $(".img-show img").attr("src", $src);
      });

      $("span, .overlay").click(function() {
        $(".show").fadeOut();
      });

    });
  </script>
</body>

</html>

<style>
  .popup {
    width: 1280px;
    margin: auto;
    text-align: center
  }

  .popup img {
    width: 390px;
    height: 293px;
    cursor: pointer
  }

  .popupthanks {
    width: 1000px;
    margin: auto;
    text-align: center
  }

  .popupthanks img {
    width: 220px;
    height: 311px;
    cursor: pointer
  }

  .popupthanks .thankspic {
    width: 440px;
    height: 311px;
    cursor: pointer
  }

  .show {
    z-index: 999;
    display: none;
  }

  .show .overlay {
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, .66);
    position: absolute;
    top: 0;
    left: 0;
  }

  .show .img-show {
    width: 600px;
    height: 400px;
    background: #FFF;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    overflow: hidden
  }

  .img-show span {
    position: absolute;
    top: 10px;
    right: 10px;
    z-index: 99;
    cursor: pointer;
  }

  .img-show img {
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
  }
</style>